### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by BlawoHD** [ExaSonit/PasswordHack-PocketMine#1]
Do you want to make plugins with me?

**Comment by ExaSonit** [comment]
I am just a simple pluginner, but I know very little about PHP and I do not know how I might be useful to you.
Ben basit bir pluginner değilim, ama PHP çok az şey biliyoruz ve nasıl yapabilirdim değerli bilmiyorum
我只是一个简单的pluginner，但我知道很少PHP的，不知道我怎么会有价值

**Comment by BlawoHD** [comment]
What is the IP of your server?

**Comment by ExaSonit** [comment]
I haven't a server. I haven't enough money to maintain a vps

**Comment by BlawoHD** [comment]
ok, Do we want to make a server?

**Comment by ExaSonit** [comment]
But I haven't money to a vps  😕

**Comment by BlawoHD** [comment]
Do you want to create plugins with me?
https://github.com/PMDE-Dev

**Comment by ExaSonit** [comment]
You are a developer, i not sorry...

**Comment by BlawoHD** [comment]
No matter, I'll help you

**Comment by ExaSonit** [comment]
But i know very little about php 😥

**Comment by BlawoHD** [comment]
I'll help you,

**Comment by ExaSonit** [comment]
Alright... I'm joined in your organization, when I study more of php?

**Comment by ExaSonit** [comment]
How i can help you? :/
